# Site title and subtitle. This is used in _includes/header.html
title: 'Glide v4'
subtitle: '빠르고 효율적인 Android 이미지 로딩 라이브러리'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/bumptech/glide'

# URL to translation repo, used in _includes/header.html
repourl: 'https://github.com/kofboy2000/glide-doc-kr'

# Documentation for other language urls, used in _includes/header.html
otherlang: [
  ['English', 'http://bumptech.github.io/glide/'],
  ['Chinese', 'https://muyangmin.github.io/glide-docs-cn/']
]

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['int', 'Integration Libraries'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/glide-doc-kr'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md', 'samples', 'testutil', 'third_party', 'library', 'build']

# Use the kramdown Markdown renderer
markdown: kramdown
kramdown:
  input: GFM

description: An image loading and caching library for Android focused on smooth scrolling
google_analytics:
show_downloads: true
theme: jekyll-theme-minimal
